# Generated by Django 5.2 on 2026-04-26 11:09

import django.db.models.deletion
import utils.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("subscriptions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Gateway",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, upload_to="gateways/", verbose_name="avatar"
                    ),
                ),
                (
                    "is_enable",
                    models.BooleanField(default=True, verbose_name="is enable"),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created time"
                    ),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="updated time"),
                ),
            ],
            options={
                "verbose_name": "Gateway",
                "verbose_name_plural": "Gateways",
                "db_table": "gateways",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.PositiveIntegerField(default=0, verbose_name="price")),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Void"),
                            (10, "Paid"),
                            (20, "Error"),
                            (30, "Canceled"),
                            (31, "Resolved"),
                        ],
                        db_index=True,
                        default=0,
                        verbose_name="status",
                    ),
                ),
                (
                    "device_uuid",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="device uuid"
                    ),
                ),
                (
                    "token",
                    models.CharField(blank=True, max_length=40, verbose_name="token"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=20,
                        validators=[utils.validators.PhoneNumberValidator()],
                        verbose_name="phone number",
                    ),
                ),
                (
                    "consumed_code",
                    models.PositiveIntegerField(
                        db_index=True, null=True, verbose_name="consumed reference code"
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created time"
                    ),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="updated time"),
                ),
                (
                    "gateway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="payments.gateway",
                        verbose_name="gateway",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="subscriptions.package",
                        verbose_name="package",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "db_table": "payments",
            },
        ),
    ]
