# Generated by Django 5.2 on 2026-03-04 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_file_options_file_file_tpe_alter_file_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="file",
            old_name="file_tpe",
            new_name="file_type",
        ),
    ]
